spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.131:3306/hotel?serverTimezone=UTC
    username: root
    password: root   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://192.168.1.131/eureka
server:
  port: 7000
